### ISSUE TITLE
Search/home missing

### ISSUE THREAD

**Issue by SwiftWinds** [SpotX-CLI/SpotX-Mac#24]
I installed SpotX but while the ads are gone, I cannot find the search or home buttons. When I use the search keyboard shortcut (Cmd+L), it doesn't show me the search bar (although search does work when I type).

Is it possible to add the missing search/home features back in?

Thank you so much for your amazing project! :)

**Comment by Nuzair46** [comment]
@SwiftWinds , can you provide a screenshot? 
also, did you add install with experimental features?

**Comment by amd64fox** [comment]
regex changed for `NEW_UI` variable

**Comment by SwiftWinds** [comment]
> can you provide a screenshot?

It seems to be fixed if I use `-o` to specify the old UI.

> also, did you add install with experimental features?

Nope.

On the other hand, though, I still get audio ads on the old UI. I'm on Spotify for macOS (Intel) 1.1.97.962.g24733a46

**Comment by jetfir3** [comment]
@SwiftWinds 

are things sorted with the following command/branch?
```
bash <(curl -sSL https://raw.githubusercontent.com/SpotX-CLI/SpotX-Mac/jet-bringup-3/install.sh)
```

**Comment by Nuzair46** [comment]
@jetfir3, close this issue if its fixed

**Comment by jetfir3** [comment]
issue fixed.
