### ISSUE TITLE
Applying Spicetify results in SpotX being unable to be installed

### ISSUE THREAD

**Issue by RWCoding58** [SpotX-CLI/SpotX-Mac#35]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of Spotify and SpotX

### Сountry of your account

Singapore

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify: 1.1.98.691
- macOS: macOS Ventura 13.1
- Shell: zsh
```

### 📝 Description

1. Run the SpotX script to install SpotX (`bash <(curl -sSL https://raw.githubusercontent.com/SpotX-CLI/SpotX-Mac/main/install.sh) -ceh -E leftsidebar` for me)
2. Run the Spicetify script to apply Spicetify (`spicetify apply`/`spicetify backup apply`, both result in the same error)
3. Rerun the SpotX script (same as step 1)

At step 3, the script returns an "xpui not found!" error and asks to reinstall Spotify. The Spotify client, SpotX and Spicetify features work, and Spicetify can still be applied; the only problem is that SpotX can't be reapplied or updated without reinstalling Spotify. Interestingly, `spicetify backup apply` does specifically say it clears the backup, but the error still occurs even when running `spicetify apply`, which doesn't say anything about that. Honestly, I'm just assuming it's okay to install Spicetify on SpotX (which I might be wrong about) because of the [FAQ section in the Windows client](https://telegra.ph/SpotX-FAQ-09-19#Can-I-use-SpotX-and-Spicetify-together?), which says it is okay to do so and recommended to install Spicetify on SpotX rather than the other way round. I apologise if I'm making any apparent mistakes, I don't know much about these things.

Edit: It appears that running `spicetify apply` overwrites all the SpotX patches, while `spicetify backup apply` doesn't.

### 🖵 Terminal Output

1. (`bash <(curl -sSL https://raw.githubusercontent.com/SpotX-CLI/SpotX-Mac/main/install.sh) -ceh -E leftsidebar`)
************************
SpotX-Mac by @SpotX-CLI
************************

Spotify version: 1.1.98.691
SpotX-Mac version: 1.1.98.691-1

Creating xpui backup...
Extracting xpui...
Applying SpotX patches...
Removing ad-related content...
Removing premium-only features...
Unlocking Spotify Connect...
Adding experimental features...
Removing logging...
Enabling new home screen UI...
Hiding non-music items on home screen...
Clearing app cache...
Rebuilding xpui...
SpotX finished patching!

2. (`spicetify apply`)
spicetify v2.14.1
Copying raw assets:
OK
Overwriting themed assets:
OK
Transferring user.css:
OK
Applying additional modifications:
OK
Transferring extensions:
OK
Transferring custom apps:
OK
success Spotify is spiced up!

OR

2. (`spicetify backup apply`)
spicetify v2.14.1
info There is available backup.
info Clear current backup:
success Backup is cleared.
Backing up app files:
OK
Extracting:
OK
Preprocessing:
info Fetching remote CSS map for newer compatible tag version: master
OK
OK
success Everything is ready, you can start applying now!
Copying raw assets:
OK
Overwriting themed assets:
OK
Transferring user.css:
OK
Applying additional modifications:
OK
Transferring extensions:
OK
Transferring custom apps:
OK
success Spotify is spiced up!

3. (`bash <(curl -sSL https://raw.githubusercontent.com/SpotX-CLI/SpotX-Mac/main/install.sh) -ceh -E leftsidebar`)
************************
SpotX-Mac by @SpotX-CLI
************************

Spotify version: 1.1.98.691
SpotX-Mac version: 1.1.98.691-1

xpui not found!
Reinstall Spotify then try again.
Exiting...

**Comment by jetfir3** [comment]
@RWCoding58 

Step #3 is expected behavior as the file that SpotX modifies has been altered by Spicetify.

Therefore, SpotX-Mac must be run before Spicetify -- SpotX will not be able to run AFTER running Spicetify unless Spotify is reinstall or upgraded -- at that point you could re-patch the reinstalled/updated client with SpotX first, then run Spicetify again. 

Is there a reason for "step 3" in your example? SpotX should only need to be run once per Spotify version. 

There should be no reason that Spicetify is reverting SpotX patches requiring SpotX to be run a second time on the same install.. unless some of the Spicetify patches/themes/whatever conflict with the SpotX patches themselves... or there are previously existing Spicetify files causing issues. Completely uninstalling Spicetify and Spotify and starting fresh should correct any issues. 

The standard workflow should be: Install/upgrade Spotify -> Run SpotX -> Run Spicetify

**Comment by Nuzair46** [comment]
@jetfir3 we can add those to a Notes section in the readme for users with spicetify

**Comment by RWCoding58** [comment]
@jetfir3 Alright, thanks for the reply. The only reason why I considered rerunning SpotX was if there was any update to the patch. Also, thanks for finding a workaround besides reinstalling the app. This would probably be helpful information that could be put on the FAQ page as well as a notes section like @Nuzair46 mentioned. Once again, I apologise for any inconvenience, as I don't know much about these things.

**Comment by jetfir3** [comment]
I may add some "spicetify detection" in the script to then add some wording to the script output. 

But, yes, we will eventually add a notes/faq section specific to macOS to address mac-specific issues as things aren't setup or handled exactly as the windows version.
