### ISSUE TITLE
Cannot reinstall after updates

### ISSUE THREAD

**Issue by paramkhodiyar** [SpotX-CLI/SpotX-Mac#43]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of Spotify and SpotX

### Сountry of your account

india

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: Spotify for macOS (Apple Silicon)
1.2.0.1165.gabf054ab
- macOS: 13.0 (22A380)
- Shell: bash
```

### 📝 Description

I had the client working but after the updates of the spotify i cannot reinstall it again, I have tried uninstalling and fresh install, but it doesnt work, as the terminal shows error

### 🖵 Terminal Output

1.Failed to connect to raw.githubusercontent.com port 443 after 75231 ms: Operation timed out

### 📸 Screenshots

<img width="567" alt="Screenshot 2022-12-19 at 1 22 11 PM" src="https://user-images.githubusercontent.com/121011079/208374644-b8cfdec7-f853-4e4f-853b-1e6b36075da1.png">

**Comment by jetfir3** [comment]
This is an issue with your ISP or network connection. They're blocking the githubusercontent domain. Use a VPN, change DNS or use a different network.
