### ISSUE TITLE
Weird UI spacing issues 

### ISSUE THREAD

**Issue by jimmysofat6864** [SpotX-CLI/SpotX-Mac#49]
Hi there is anybody else seeing these weird UI spacing issues or is it just me. Seems like it's a Mac thing. I have photos attached below. 

<img width="612" alt="Screen Shot 2023-01-19 at 8 15 46 PM" src="https://user-images.githubusercontent.com/69532417/213616402-951758cb-5de5-4a92-a2bd-df6057112849.png">
<img width="1091" alt="Screen Shot 2023-01-19 at 8 13 30 PM" src="https://user-images.githubusercontent.com/69532417/213616406-e26ae89c-86d5-454b-a55d-4ecb7b3977e4.png">

**Comment by Enoch-Liu1** [comment]
I have the same issue. The lyrics button on the bottom has also disappeared for me

**Comment by Nuzair46** [comment]
Can you guys make sure its caused by SpotX or not by uninstalling SpotX and see if the issue persists.

If you are using the new experimental UI thats locked in Stock spotify mac, its probably an issue with that. Just stop using the new UI until spotify fixes it

**Comment by jetfir3** [comment]
No proper bug report filled out using provided template. Not enough info. 

If updating to latest v1.2.3.x build -- it's not yet supported by SpotX-Mac as the `readme` states.

**Comment by jimmysofat6864** [comment]
> No proper bug report filled out using provided template. Not enough info.
> 
> If updating to latest v1.2.3.x build -- ~it's not yet supported by SpotX-Mac as the `readme` states~ 1.2.3.1115 is now supported by SpotX-Mac.
> 
> In the future, take note of latest supported version in `readme` and use the provided bug report template which removes any guessing games.

Ok just checked it works now after reinstallation and reapplying patch. Turns out it was the newest version that wasn't supported. For some reason when I tried to open my issue there was no template but it's there now.

**Comment by jimmysofat6864** [comment]
> Can you guys make sure its caused by SpotX or not by uninstalling SpotX and see if the issue persists.
> 
> If you are using the new experimental UI thats locked in Stock spotify mac, its probably an issue with that. Just stop using the new UI until spotify fixes it

I tried to use the -o flag during installation but it didn't work for some reason but new UI works now so it's ok now. I entered `bash <(curl -sSL https://raw.githubusercontent.com/SpotX-CLI/SpotX-Mac/main/install.sh) -o
`

and it gave me some error message of some sort but it's doesn't matter anymore as new UI works now.

**Comment by Enoch-Liu1** [comment]
The lyrics button on the bottom still isn't showing for me

**Comment by jimmysofat6864** [comment]
> The lyrics button on the bottom still isn't showing for me

@Enoch-Liu1 You have to reinstall Spotify via the installer then reapply the patch. Then the lyrics button has changed and it's moved to the left. It's to the right of the queue button in the latest update.

**Comment by Enoch-Liu1** [comment]
It still doesn't work.

**Comment by jimmysofat6864** [comment]
Again the new Spotify update removed the lyrics button that has nothing to
do with the patch. Even if you don’t patch it the lyrics button is still
gone they replaced it with something else.

**Comment by Enoch-Liu1** [comment]
Ok thanks
