### ISSUE TITLE
Does SpotX for Mac have the updated UI like the Windows one?

### ISSUE THREAD

**Issue by jdrgnas** [SpotX-CLI/SpotX-Mac#53]
Title

**Comment by sybercorp** [comment]
I'm on macOS and had no idea there was a UI at all (on any platform).  I just run the Bash script to install/update/modify SpotX, and figured that's all there was.  What do you need a UI for?

**Comment by jimmysofat6864** [comment]
Yes it does. It's the one where the album art now can show up on the right side of the display instead.

**Comment by jdrgnas** [comment]
For some reason I do not get the new UI, I do the install command: 

"bash <(curl -sSL https://raw.githubusercontent.com/SpotX-CLI/SpotX-Mac/main/install.sh) -ceu"

Anyone had this issue as well?

**Comment by Nuzair46** [comment]
The new UI in macOS seems to be broken. It is recommended to not use it for now.
