### ISSUE TITLE
Odd spacing issues after newest Spotify update 

### ISSUE THREAD

**Issue by jimmysofat6864** [SpotX-CLI/SpotX-Mac#54]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of Spotify and SpotX

### Сountry of your account

United States

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: Spotify for macOS (Intel)1.2.4.912.g949d5fd0
- macOS: 12.16.3
- Shell: zsh
```

### 📝 Description

1. Install Spotify
2. Install Patch
3. See interface looks off. 

### 🖥️ Terminal Input/Output

************************
SpotX-Mac by @SpotX-CLI
************************

Spotify version: 1.2.4.912
SpotX-Mac version: 1.2.3.1115-1

SpotX backup found, SpotX has already been used on this install.
Re-run SpotX using the '-f' flag to force xpui patching.

Skipping xpui patches and continuing SpotX...
Applying SpotX patches...
SpotX finished patching!

### 📸 Screenshots

<img width="947" alt="Screen Shot 2023-02-12 at 12 08 00 AM" src="https://user-images.githubusercontent.com/69532417/218299984-c0e5294e-f6e7-4af7-bad5-425deb985fe5.png">
<img width="242" alt="Screen Shot 2023-02-12 at 12 08 53 AM" src="https://user-images.githubusercontent.com/69532417/218300012-3f43046c-8d81-4f0d-a16d-8baa6b57fedd.png">

**Comment by Nuzair46** [comment]
Don't use the experimental UI.
