### ISSUE TITLE
New version (1.2.6.863) not working properly with script

### ISSUE THREAD

**Issue by hackingguy** [SpotX-CLI/SpotX-Mac#55]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of Spotify and SpotX

### Сountry of your account

India

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.6.863
- macOS: Ventura
- Shell: zsh
```

### 📝 Description

UI seems messed up even after reinstalling in newer spotify version.

### 🖥️ Terminal Input/Output

Input
```
bash <(curl -sSL https://raw.githubusercontent.com/SpotX-CLI/SpotX-Mac/main/install.sh)
```

Output
```
************************
SpotX-Mac by @SpotX-CLI
************************

Spotify version: 1.2.6.863
SpotX-Mac version: 1.2.3.1115-1

Creating xpui backup...
Extracting xpui...
Applying SpotX patches...
Removing ad-related content...
Removing premium-only features...
Unlocking Spotify Connect...
Removing logging...
Enabling new home screen UI...
Rebuilding xpui...
SpotX finished patching!
```

### 📸 Screenshots

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/28388650/222890156-a51081f8-ec45-4899-bf0e-fd59c02d80e0.png">

<img width="667" alt="image" src="https://user-images.githubusercontent.com/28388650/222890121-125c8716-f2c0-4234-be84-81b52be23975.png">

**Comment by Nuzair46** [comment]
use `-o` flag
