### ISSUE TITLE
bug on interface font, home, search bar

### ISSUE THREAD

**Issue by termaulmaul** [SpotX-CLI/SpotX-Mac#57]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of Spotify and SpotX

### Сountry of your account

Indonesia

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify: 
- macOS: 
- Shell:
```

### 📝 Description

bug on interface font, home, search bar

### 🖥️ Terminal Input/Output

bug on interface font, home, search bar

### 📸 Screenshots

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/109366541/224494045-3d6319ba-31d6-4568-8d7a-e14bbdb980ae.png">

**Comment by Nuzair46** [comment]
install with `- o` flag
