### ISSUE TITLE
What are the Experimental features ?

### ISSUE THREAD

**Issue by nasw1h** [SpotX-CLI/SpotX-Mac#60]

**Comment by claudiusraphael** [comment]
Bump ...

The link in the README points to issue 50 which is non-existent and so GitHub switches to issue#50 in pull requests (which is also shown only when logged in, otherwise 404).

So yeah, what are the experimental features?

Kind of important to know, since in the README flags "-ceu" (e = experimental) is used as one example.

**Comment by Geczy** [comment]
# Experimental (A/B test) features

- **ENABLE_ADD_PLAYLIST** 
  - Enable support for adding a playlist to another playlist
- **ENABLE_BAD_BUNNY** 
  - Enable a different heart button for Bad Bunny
- **ENABLE_BALLOONS** 
  - Enable showing balloons on album release date anniversaries
- **ENABLE_BLOCK_USERS** 
  - Enable block users feature in clientX
- **ENABLE_CAROUSELS** 
  - Use carousels on Home
- **ENABLE_CLEAR_DOWNLOADS** 
  - Enable option in settings to clear all downloads
- **ENABLE_DEVICE_LIST_LOCAL** 
  - Enable splitting the device list based on local network
- **ENABLE_DISCOG_SHELF** 
  - Enable a condensed disography shelf on artist pages
- **ENABLE_ENHANCE_PLAYLIST** 
  - Enable Enhance Playlist UI and functionality for end-users
- **ENABLE_ENHANCE_SONGS** 
  - Enable Enhance Liked Songs UI and functionality
- **ENABLE_EQUALIZER** 
  - Enable audio equalizer for Desktop and Web Player
- **ENABLE_FOLLOWERS_ON_PROFILE** 
  - Enable a setting to control if followers and following lists are shown on profile
- **ENABLE_FORGET_DEVICES** 
  - Enable the option to Forget Devices
- **ENABLE_IGNORE_REC** 
  - Enable Ignore In Recommendations for desktop and web
- **ENABLE_LIKED_SONGS** 
  - Enable Liked Songs section on Artist page
- **ENABLE_LYRICS_CHECK** 
  - With this enabled, clients will check whether tracks have lyrics available
- **ENABLE_LYRICS_MATCH** 
  - Enable Lyrics match labels in search results
- **ENABLE_PATHFINDER_DATA** 
  - Fetch Browse data from Pathfinder
- **ENABLE_PLAYLIST_CREATION_FLOW** 
  - Enables new playlist creation flow in Web Player and DesktopX
- **ENABLE_PLAYLIST_PERMISSIONS_FLOWS** 
  - Enable Playlist Permissions flows for Prod
- **ENABLE_PODCAST_PLAYBACK_SPEED** 
  - playback speed range from 0.5-3.5 with every 0.1 increment
- **ENABLE_PODCAST_TRIMMING** 
  - Enable silence trimming in podcasts
- **ENABLE_SEARCH_BOX** 
  - Adds a search box so users are able to filter playlists when trying to add songs to a playlist using the contextmenu
- **ENABLE_SIMILAR_PLAYLIST** 
  - Enable Similar Playlists feature

**Comment by claudiusraphael** [comment]
Thanks @Nuzair46 for providing this list in this (searchable) issue!

**Comment by Geczy** [comment]
that was me tho
