### ISSUE TITLE
UI changes to old even without -o flag

### ISSUE THREAD

**Issue by Devnol** [SpotX-CLI/SpotX-Mac#61]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of Spotify and SpotX

### Сountry of your account

Greece

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: Spotify for macOS (Intel) 1.2.13.661.ga588f749
- macOS: Monterey 12.6.6
- Shell: zsh (iTerm2)
```

### 📝 Description

Latest Spotify version shows older UI after patching with SpotX, even without the -o flag
To reproduce:
1. Install latest spotify, open to see new UI
2. Patch with spotX, without the -o flag, clear cache for good measure
3. Reopen spotify, see older UI.
The same behavior happens if patched WITH the -o flag as well (ran uninstall script between attempts obviously)

### 🖥️ Terminal Input/Output

`~$ bash <(curl -sSL https://raw.githubusercontent.com/SpotX-CLI/SpotX-Mac/main/install.sh) -ce`
```
************************
SpotX-Mac by @SpotX-CLI
************************

Spotify version: 1.2.13.661
SpotX-Mac version: 1.2.3.1115-1

Creating xpui backup...
Extracting xpui...
Applying SpotX patches...
Removing ad-related content...
Removing premium-only features...
Unlocking Spotify Connect...
Adding experimental features...
Removing logging...
Enabling new home screen UI...
Clearing app cache...
Rebuilding xpui...
SpotX finished patching!
```

### 📸 Screenshots

Unpatched Spotify Free:
![Screenshot 2023-06-18 at 22 37 15](https://github.com/SpotX-CLI/SpotX-Mac/assets/58105634/0679c012-bfcd-42eb-b352-3d49b1c9d115)

Patched with -ce command line options:
![Screenshot 2023-06-18 at 22 41 02](https://github.com/SpotX-CLI/SpotX-Mac/assets/58105634/9ef69b06-4710-43b7-bb3a-1b136e14dbc4)

Patched with -ceo command line options:
![Screenshot 2023-06-18 at 22 39 46](https://github.com/SpotX-CLI/SpotX-Mac/assets/58105634/0ff21371-6f41-469f-a555-00b5c1dadeba)

**Comment by Nuzair46** [comment]
same as #59

**Comment by Devnol** [comment]
Hello, how is that same as #59 ? I am not getting spacing issues as they are and I am not using the -o flag. I have no issue moving to a fork but I would rather know what exactly is causing that and how it can be fixed on this repo rather than some other fork but I don't see why this repo would continue to provide code that is clearly half-broken, without at least having proved it's not just my issue.

**Comment by Nuzair46** [comment]
@Devnol the original issue is same issue. the o flag is broken. since you have the issue without using o flag, i think its an issue with patch and patch needs to be updated

**Comment by Devnol** [comment]
I see, so should I just switch to that fork

**Comment by Devnol** [comment]
Huh, I know this issue is closed but it looks like now the old ui doesn't appear at all (even with the -o) flag but the new ui does, so I guess it's slightly better now but still broken
