### ISSUE TITLE
Disables Lyrics

### ISSUE THREAD

**Issue by Whobler** [SpotX-CLI/SpotX-Mac#62]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of Spotify and SpotX

### Сountry of your account

United States

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: Spotify for macOS (Apple Silicon)
1.2.14.1149.ga3ae422d
- macOS: Ventura 13.4.1 
- Shell: zsh
```

### 📝 Description

The lyrics option completely disappeared from the Spotify client.

### 🖥️ Terminal Input/Output

Working as normal - no errors

**Comment by Geczy** [comment]
works for me. try a popular song  

<img width="858" alt="CleanShot 2023-07-01 at 10 54 45@2x" src="https://github.com/SpotX-CLI/SpotX-Mac/assets/1036968/a8974452-f85f-429d-90ca-0aed63f10ca7">

**Comment by Nuzair46** [comment]
probably because the song itself don't have lyrics added.
