### ISSUE TITLE
Feature rq: remove recommended songs from playlists

### ISSUE THREAD

**Issue by MeechaPooch** [SpotX-CLI/SpotX-Mac#63]
Can you add an option to remove this section below playlists?
<img width="292" alt="image" src="https://github.com/SpotX-CLI/SpotX-Mac/assets/55720333/54b1e29a-e3c8-46cd-a5d2-482c868184cb">
I disagree with using the internet to find new songs. Its all distraction and no heart. Ive found all my years of music that I love from record stores and friends. Literally nothing from this emotionless list.
Please let me do away with it
<3 Lovingly
Micah

**Comment by Geczy** [comment]
where's that? show the full ui

<img width="839" alt="CleanShot 2023-07-01 at 10 53 38@2x" src="https://github.com/SpotX-CLI/SpotX-Mac/assets/1036968/ef38fe29-b97e-4297-afb0-5321dc746c39">

**Comment by Nuzair46** [comment]
This feels unrequired for the wider users. something we don't want to focus on. You can ask the Spicetify community if some theme does this already
